[2022-04-07 00:01:08,945] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-04-06T18:00:00+00:00 [queued]>
[2022-04-07 00:01:08,949] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-04-06T18:00:00+00:00 [queued]>
[2022-04-07 00:01:08,949] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 00:01:08,949] {taskinstance.py:1043} INFO - Starting attempt 2 of 6
[2022-04-07 00:01:08,949] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 00:01:08,956] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-04-06T18:00:00+00:00
[2022-04-07 00:01:08,958] {standard_task_runner.py:52} INFO - Started process 50297 to run task
[2022-04-07 00:01:08,964] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-04-06T18:00:00+00:00', '--job-id', '75', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmps5eybywf', '--error-file', '/tmp/tmpimbje9w9']
[2022-04-07 00:01:08,965] {standard_task_runner.py:77} INFO - Job 75: Subtask run_script
[2022-04-07 00:01:08,989] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-04-06T18:00:00+00:00 [running]> on host 193e33218975
[2022-04-07 00:01:09,003] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-06T18:00:00+00:00
[2022-04-07 00:01:09,003] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-04-07 00:01:09,004] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-04-07 00:01:09,008] {bash.py:169} INFO - Output:
[2022-04-07 00:01:10,989] {bash.py:173} INFO - Spain
[2022-04-07 00:01:10,989] {bash.py:173} INFO - 27751
[2022-04-07 00:01:10,990] {bash.py:173} INFO - Portugal
[2022-04-07 00:01:10,990] {bash.py:173} INFO - 6600
[2022-04-07 00:01:10,990] {bash.py:173} INFO - Spain: CO2 203, mix [('wind', 9153, '33'), ('gas', 7557, '27'), ('nuclear', 5827, '21')]
[2022-04-07 00:01:10,990] {bash.py:173} INFO - Portugal: CO2 215, mix [('wind', 2503, '38'), ('gas', 2491, '38'), ('hydro', 905, '14')]
[2022-04-07 00:01:10,990] {bash.py:173} INFO - Denmark
[2022-04-07 00:01:10,990] {bash.py:173} INFO - 4054
[2022-04-07 00:01:10,990] {bash.py:173} INFO - Sweden
[2022-04-07 00:01:10,990] {bash.py:173} INFO - 16231
[2022-04-07 00:01:10,990] {bash.py:173} INFO - Denmark: CO2 145, mix [('wind', 2337, '58'), ('biomass', 631, '16'), ('coal', 377, '9')]
[2022-04-07 00:01:10,990] {bash.py:173} INFO - Sweden: CO2 39, mix [('hydro', 7040, '43'), ('nuclear', 5494, '34'), ('wind', 2371, '15')]
[2022-04-07 00:01:10,990] {bash.py:173} INFO - Traceback (most recent call last):
[2022-04-07 00:01:10,990] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-04-07 00:01:10,990] {bash.py:173} INFO -     get_matchups()
[2022-04-07 00:01:10,990] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-04-07 00:01:10,990] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-04-07 00:01:10,990] {bash.py:173} INFO -   File "/app/scripts/main.py", line 198, in get_data
[2022-04-07 00:01:10,991] {bash.py:173} INFO -     co2_country1 = get_co2(country1)
[2022-04-07 00:01:10,991] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-04-07 00:01:10,991] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-04-07 00:01:10,991] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-04-07 00:01:10,991] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-04-07 00:01:10,991] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-04-07 00:01:11,027] {bash.py:177} INFO - Command exited with return code 1
[2022-04-07 00:01:11,035] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-04-07 00:01:11,037] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220406T180000, start_date=20220407T000108, end_date=20220407T000111
[2022-04-07 00:01:11,060] {local_task_job.py:146} INFO - Task exited with return code 1
