[2022-04-07 00:02:12,112] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-04-06T18:00:00+00:00 [queued]>
[2022-04-07 00:02:12,118] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-04-06T18:00:00+00:00 [queued]>
[2022-04-07 00:02:12,118] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 00:02:12,118] {taskinstance.py:1043} INFO - Starting attempt 3 of 6
[2022-04-07 00:02:12,118] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-04-07 00:02:12,125] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-04-06T18:00:00+00:00
[2022-04-07 00:02:12,127] {standard_task_runner.py:52} INFO - Started process 50314 to run task
[2022-04-07 00:02:12,132] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-04-06T18:00:00+00:00', '--job-id', '76', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmp_wi210oe', '--error-file', '/tmp/tmp0ancbwjk']
[2022-04-07 00:02:12,132] {standard_task_runner.py:77} INFO - Job 76: Subtask run_script
[2022-04-07 00:02:12,154] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-04-06T18:00:00+00:00 [running]> on host 193e33218975
[2022-04-07 00:02:12,168] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-04-06T18:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-06T18:00:00+00:00
[2022-04-07 00:02:12,168] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-04-07 00:02:12,168] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-04-07 00:02:12,174] {bash.py:169} INFO - Output:
[2022-04-07 00:02:15,177] {bash.py:173} INFO - Italy
[2022-04-07 00:02:15,178] {bash.py:173} INFO - 30078
[2022-04-07 00:02:15,178] {bash.py:173} INFO - Spain
[2022-04-07 00:02:15,178] {bash.py:173} INFO - 27751
[2022-04-07 00:02:15,178] {bash.py:173} INFO - Italy: CO2 430, mix [('gas', 17709, '59'), ('coal', 3072, '10'), ('wind', 2764, '9')]
[2022-04-07 00:02:15,178] {bash.py:173} INFO - Spain: CO2 203, mix [('wind', 9153, '33'), ('gas', 7557, '27'), ('nuclear', 5827, '21')]
[2022-04-07 00:02:15,178] {bash.py:173} INFO - Sweden
[2022-04-07 00:02:15,178] {bash.py:173} INFO - 16231
[2022-04-07 00:02:15,178] {bash.py:173} INFO - Finland
[2022-04-07 00:02:15,178] {bash.py:173} INFO - 9330
[2022-04-07 00:02:15,178] {bash.py:173} INFO - Sweden: CO2 39, mix [('hydro', 7040, '43'), ('nuclear', 5494, '34'), ('wind', 2371, '15')]
[2022-04-07 00:02:15,178] {bash.py:173} INFO - Finland: CO2 167, mix [('nuclear', 3580, '38'), ('hydro', 1741, '19'), ('wind', 1345, '14')]
[2022-04-07 00:02:15,178] {bash.py:173} INFO - Traceback (most recent call last):
[2022-04-07 00:02:15,178] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-04-07 00:02:15,178] {bash.py:173} INFO -     get_matchups()
[2022-04-07 00:02:15,178] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-04-07 00:02:15,178] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-04-07 00:02:15,178] {bash.py:173} INFO -   File "/app/scripts/main.py", line 198, in get_data
[2022-04-07 00:02:15,178] {bash.py:173} INFO -     co2_country1 = get_co2(country1)
[2022-04-07 00:02:15,178] {bash.py:173} INFO -   File "/app/scripts/main.py", line 73, in get_co2
[2022-04-07 00:02:15,178] {bash.py:173} INFO -     country_consumption_total = get_total_consumption(country)
[2022-04-07 00:02:15,178] {bash.py:173} INFO -   File "/app/scripts/main.py", line 66, in get_total_consumption
[2022-04-07 00:02:15,179] {bash.py:173} INFO -     country_consumption_total.append(sum(res.get('powerConsumptionBreakdown').values()))
[2022-04-07 00:02:15,179] {bash.py:173} INFO - AttributeError: 'NoneType' object has no attribute 'values'
[2022-04-07 00:02:15,213] {bash.py:177} INFO - Command exited with return code 1
[2022-04-07 00:02:15,221] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-04-07 00:02:15,223] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220406T180000, start_date=20220407T000212, end_date=20220407T000215
[2022-04-07 00:02:15,274] {local_task_job.py:146} INFO - Task exited with return code 1
