[2022-03-17 12:05:22,549] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-17T06:00:00+00:00 [queued]>
[2022-03-17 12:05:22,555] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-17T06:00:00+00:00 [queued]>
[2022-03-17 12:05:22,555] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 12:05:22,555] {taskinstance.py:1043} INFO - Starting attempt 6 of 6
[2022-03-17 12:05:22,555] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 12:05:22,562] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-17T06:00:00+00:00
[2022-03-17 12:05:22,566] {standard_task_runner.py:52} INFO - Started process 383160 to run task
[2022-03-17 12:05:22,572] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-17T06:00:00+00:00', '--job-id', '360', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmp5lizpqm3', '--error-file', '/tmp/tmplfsj7pfn']
[2022-03-17 12:05:22,572] {standard_task_runner.py:77} INFO - Job 360: Subtask run_script
[2022-03-17 12:05:22,603] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-17T06:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-17 12:05:22,621] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-17T06:00:00+00:00
[2022-03-17 12:05:22,622] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-17 12:05:22,622] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-17 12:05:22,629] {bash.py:169} INFO - Output:
[2022-03-17 12:05:22,893] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-17 12:05:22,893] {bash.py:173} INFO -   File "/app/scripts/main.py", line 10, in <module>
[2022-03-17 12:05:22,893] {bash.py:173} INFO -     conn = psycopg2.connect(f"host={host} dbname={dbname} user={user} password={password}")
[2022-03-17 12:05:22,893] {bash.py:173} INFO -   File "/app/env/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
[2022-03-17 12:05:22,894] {bash.py:173} INFO -     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2022-03-17 12:05:22,894] {bash.py:173} INFO - psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution
[2022-03-17 12:05:22,894] {bash.py:173} INFO - 
[2022-03-17 12:05:22,925] {bash.py:177} INFO - Command exited with return code 1
[2022-03-17 12:05:22,935] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-17 12:05:22,937] {taskinstance.py:1496} INFO - Marking task as FAILED. dag_id=matchup, task_id=run_script, execution_date=20220317T060000, start_date=20220317T120522, end_date=20220317T120522
[2022-03-17 12:05:22,986] {local_task_job.py:146} INFO - Task exited with return code 1
