[2022-03-15 12:00:03,638] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-15T06:00:00+00:00 [queued]>
[2022-03-15 12:00:03,643] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: matchup.run_script 2022-03-15T06:00:00+00:00 [queued]>
[2022-03-15 12:00:03,644] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 12:00:03,644] {taskinstance.py:1043} INFO - Starting attempt 1 of 6
[2022-03-15 12:00:03,644] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-15 12:00:03,652] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): run_script> on 2022-03-15T06:00:00+00:00
[2022-03-15 12:00:03,656] {standard_task_runner.py:52} INFO - Started process 354582 to run task
[2022-03-15 12:00:03,663] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'matchup', 'run_script', '2022-03-15T06:00:00+00:00', '--job-id', '318', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/matchup.py', '--cfg-path', '/tmp/tmpgfx0lv2s', '--error-file', '/tmp/tmp68w2l1pa']
[2022-03-15 12:00:03,664] {standard_task_runner.py:77} INFO - Job 318: Subtask run_script
[2022-03-15 12:00:03,695] {logging_mixin.py:104} INFO - Running <TaskInstance: matchup.run_script 2022-03-15T06:00:00+00:00 [running]> on host 531edfb863fc
[2022-03-15 12:00:03,718] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=r.chesne@gmail.com
AIRFLOW_CTX_DAG_OWNER=Robin
AIRFLOW_CTX_DAG_ID=matchup
AIRFLOW_CTX_TASK_ID=run_script
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T06:00:00+00:00
[2022-03-15 12:00:03,719] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-15 12:00:03,719] {bash.py:158} INFO - Running command: python /app/scripts/main.py
[2022-03-15 12:00:03,727] {bash.py:169} INFO - Output:
[2022-03-15 12:00:09,960] {bash.py:173} INFO - Spain
[2022-03-15 12:00:09,961] {bash.py:173} INFO - 31909
[2022-03-15 12:00:09,961] {bash.py:173} INFO - Italy
[2022-03-15 12:00:09,961] {bash.py:173} INFO - 42661
[2022-03-15 12:00:09,961] {bash.py:173} INFO - Spain: CO2 150, mix [('wind', 11861, '37'), ('gas', 6031, '19'), ('nuclear', 5483, '17')]
[2022-03-15 12:00:09,961] {bash.py:173} INFO - Italy: CO2 359, mix [('gas', 22970, '54'), ('solar', 7281, '17'), ('hydro', 2708, '6')]
[2022-03-15 12:00:09,961] {bash.py:173} INFO - Finland
[2022-03-15 12:00:09,961] {bash.py:173} INFO - 9857
[2022-03-15 12:00:09,961] {bash.py:173} INFO - Norway
[2022-03-15 12:00:09,961] {bash.py:173} INFO - 18334
[2022-03-15 12:00:09,964] {bash.py:173} INFO - Traceback (most recent call last):
[2022-03-15 12:00:09,964] {bash.py:173} INFO -   File "/app/scripts/main.py", line 241, in <module>
[2022-03-15 12:00:09,964] {bash.py:173} INFO -     get_matchups()
[2022-03-15 12:00:09,964] {bash.py:173} INFO -   File "/app/scripts/main.py", line 51, in get_matchups
[2022-03-15 12:00:09,964] {bash.py:173} INFO -     get_data(division, country1, country2)
[2022-03-15 12:00:09,964] {bash.py:173} INFO -   File "/app/scripts/main.py", line 201, in get_data
[2022-03-15 12:00:09,964] {bash.py:173} INFO -     mix_country2 = get_mix(country2)
[2022-03-15 12:00:09,964] {bash.py:173} INFO -   File "/app/scripts/main.py", line 105, in get_mix
[2022-03-15 12:00:09,965] {bash.py:173} INFO -     res = requests.get(f"https://api.electricitymap.org/v3/power-breakdown/latest?zone={zone}", headers={'auth-token':electricitymap_token}).json()
[2022-03-15 12:00:09,965] {bash.py:173} INFO -   File "/app/env/lib/python3.8/site-packages/requests/models.py", line 898, in json
[2022-03-15 12:00:09,965] {bash.py:173} INFO -     return complexjson.loads(self.text, **kwargs)
[2022-03-15 12:00:09,965] {bash.py:173} INFO -   File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
[2022-03-15 12:00:09,965] {bash.py:173} INFO -     return _default_decoder.decode(s)
[2022-03-15 12:00:09,965] {bash.py:173} INFO -   File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
[2022-03-15 12:00:09,965] {bash.py:173} INFO -     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2022-03-15 12:00:09,965] {bash.py:173} INFO -   File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
[2022-03-15 12:00:09,965] {bash.py:173} INFO -     raise JSONDecodeError("Expecting value", s, err.value) from None
[2022-03-15 12:00:09,965] {bash.py:173} INFO - json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[2022-03-15 12:00:10,008] {bash.py:177} INFO - Command exited with return code 1
[2022-03-15 12:00:10,017] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/app/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/app/env/lib/python3.8/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-15 12:00:10,020] {taskinstance.py:1496} INFO - Marking task as UP_FOR_RETRY. dag_id=matchup, task_id=run_script, execution_date=20220315T060000, start_date=20220315T120003, end_date=20220315T120010
[2022-03-15 12:00:10,046] {local_task_job.py:146} INFO - Task exited with return code 1
